'use client';

import { FormEvent, useState } from 'react';

export default function investmentEditor({ investment }: { investment: { id: string; name: string; bio: string | null; location: string | null; status: string; isFeatured: boolean; isTrending: boolean } }) {
  const [form, setForm] = useState(investment); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  const set = (key: keyof typeof form, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  async function save(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(''); const response = await fetch(`/api/admin/investments/${investment.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); setSaving(false); setMessage(response.ok ? 'Saved.' : data.error || 'Unable to save changes.'); }
  return <form onSubmit={save} className="space-y-4 rounded-xl bg-white p-6 shadow-sm"><h2 className="text-lg font-bold">Profile settings</h2><label className="block text-sm font-medium">Name<input required value={form.name} onChange={(e) => set('name', e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">Location<input value={form.location || ''} onChange={(e) => set('location', e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">Biography<textarea value={form.bio || ''} onChange={(e) => set('bio', e.target.value)} rows={5} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></label><label className="block text-sm font-medium">Status<select value={form.status} onChange={(e) => set('status', e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></label><div className="flex gap-5"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isFeatured} onChange={(e) => set('isFeatured', e.target.checked)} /> Featured</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.isTrending} onChange={(e) => set('isTrending', e.target.checked)} /> Trending</label></div>{message && <p className="text-sm text-emerald-700">{message}</p>}<button disabled={saving} className="rounded-lg bg-emerald-700 px-4 py-2 font-semibold text-white disabled:opacity-60">{saving ? 'Saving…' : 'Save changes'}</button></form>;
}
